### ISSUE TITLE
Send reminder texts

### ISSUE THREAD

**Issue by clark-teeple** [SanctuaryRefugeeHealth/sanctuary-patient-api#15]
# Overview
Text messages need to be sent at some point prior to the appointment.

# Requirements
Send text message with appointment reminder in whatever language is specified in the appointment to the phone number specified in the appointment if the appointment date/time falls within whatever interval we decide makes sense.

Scheduler will need to authenticate.

Might make sense to track whether or not an appointment reminder has been sent for an appointment record.

# Unknowns
When we should send texts relative to appointment.

If we should send more than one.

If we should get confirmation from recipient ("reply C to confirm" kinda thing).

Best option for this.

**Comment by iamstevedavis** [comment]
A lambda might work. We could even do all the actual work in the API of this project and all the lambda does is fire up at 7am every day and authenticate then call one of our API routes.

**Comment by clark-teeple** [comment]
lol I knew you were going to say that. no objections here, seems like the easiest way. make a route that returns all the appointment IDs that need a message and hit the POST appointment/:id/messages.

**Comment by iamstevedavis** [comment]
We don't even need to put any code in the lambda. We could make a route called `sendMessages` in our API that does all the lookups and calls twilio and all the lambda does is call that route so it knows it's time to execute. Basically like a push notification to our API... a webhook even?

**Comment by clark-teeple** [comment]
Even better. If you set up the lambda, I can make the route.

**Comment by KrisBraun** [comment]
For MVP, it would be acceptable to simply send the message once, immediately. It makes sense to let people know ASAP. Looks like #12 does that.

Then, reminders could be very helpful. So this PR could add one or two reminders in addition to the original message. I'd suggest this:
1. If the appointment is tomorrow, and the original message was sent earlier than today, send one at 9 am.
2. If the appointment is today, and the original message was sent earlier than today, send one at 8 am.

**Comment by KrisBraun** [comment]
We want to handle replies eventually for sure. I suggest doing that in a separate PR.

**Comment by KrisBraun** [comment]
Re-reading my suggestion 👆, maybe we simplify by running a single job at 8 am every day.

**Comment by Wiles** [comment]
@clark-teeple @iamstevedavis Twilio has a [tutorial](https://www.twilio.com/docs/sms/tutorials/appointment-reminders-node-express) which uses [node-cron](https://github.com/kelektiv/node-cron) instead of a Lambda. Was this approach considered?

**Comment by KrisBraun** [comment]
@Wiles I don't think we were aware of that option. This PR has sat for a while, without a clear next step, so I think it's fair to attempt an alternate approach. This is a feature I know would really help add value!

**Comment by iamstevedavis** [comment]
I had brought up changing to a Cron job instead of a lambda. I already had this lambda made for another project so I just put this up back when I was brought on board to get something up but it won't ever go in because the infrastructure doesn't exist.

**Comment by Wiles** [comment]
@KrisBraun Is our API deployment single instance? One issue with the `node-cron` approach is that we need to ensure it only runs in one place if/when it is multi-instance.

**Comment by KrisBraun** [comment]
Yes, the API is single instance now and for the foreseeable future.
