### ISSUE TITLE
Add country code to phone numbers

### ISSUE THREAD

**Issue by KrisBraun** [SanctuaryRefugeeHealth/sanctuary-patient-api#37]
Receiving this response from sendMessage -- I believe it's because we don't add/enforce country codes:

```
{"error":{"status":400,"message":"Permission to send an SMS has not been enabled for the region indicated by the 'To' number: 22607506674.","code":21408,"moreInfo":"https://www.twilio.com/docs/errors/21408"},"message":"Failed to send appointment reminder"}
```

For user experience, we should simply validate phone numbers have at least 7 digits. If they only have 7, we can add 1 as the country code.

**Comment by KrisBraun** [comment]
Verified country code is required by testing.

I believe we should handle this by:
[] stripping anything other than digits before saving the phone number
[] validating the number of digits (at least 7)
[] prefixing 1 is there are 7 digits

This way, phone numbers are stored in a normalized way and can be searched and compared.

**Comment by Wiles** [comment]
Are we expecting numbers with country codes other than 1? If not we could do something as simple as checking if the number starts with 1 and if not add it. 

If we are expecting other country codes a drop down in the form may be a good idea. Twilio does it like this:

![phone-1](https://user-images.githubusercontent.com/5401207/86513349-7ebaa180-bdd7-11ea-8fa9-9e24201b0041.png)

![phone-2](https://user-images.githubusercontent.com/5401207/86513352-82e6bf00-bdd7-11ea-9058-d6c2a75dc525.png)

**Comment by KrisBraun** [comment]
I think it's reasonable to limit to +1 for now, since all Sanctuary's
patients are local, and E doubt they make long distance calls to them.
