### ISSUE TITLE
One-step API deploy

### ISSUE THREAD

**Issue by KrisBraun** [SanctuaryRefugeeHealth/sanctuary-patient-api#39]
Would be great to run a single command to update the production API. Current steps:
1. make build
1. make push
1. ssh into server for the rest
1. pull the image (pull.sh)
1. stop the current container
1. start the new image

**Comment by garethbdavis** [comment]
I suspect the simplest way to do this would be to add to the makefile with each distinct action being a separate command.  That would leave flexibility to run individual steps while allowing a full deploy via something like: 
`make login build push remote-pull remote-switch-container`
