### ISSUE TITLE
Support text replies

### ISSUE THREAD

**Issue by KrisBraun** [SanctuaryRefugeeHealth/sanctuary-patient-api#53]
Three valid replies to text are allowed. We should support them in all supported languages.

1. yes
2. no
3. interpreter

The schema should be updated to record any of these replies.

If any other reply is given, the existing response should be returned.

**Comment by Wiles** [comment]
What happens for when interpreter is sent?

Also if a number has multiple upcoming appointments how should that be handled.

**Comment by KrisBraun** [comment]
The "interpreter" response should be treated as a third value alongside "yes" and "no" -- stored and visible in the table.

We haven't discussed multiple upcoming appointments with Sanctuary yet. As a first pass, let's assume we can mark all upcoming appointments with the response provided. I'll follow up with them to see if they'd like anything different.

**Comment by iamstevedavis** [comment]
Is there the possibility of being in a situation where the same phone number is used for multiple people's appointments? I am thinking of a mom who takes care of grandma and daughter and we have an appointment for more than one of these three people scheduled at some point in the future.

**Comment by iamstevedavis** [comment]
Spoke with @Wiles and best path for now is to keep it simple and just assume phone number == patient.

**Comment by iamstevedavis** [comment]
I think we also need something in place to tell them what they can reply with and what each response will do.

**Comment by Wiles** [comment]
@iamstevedavis See https://github.com/SanctuaryRefugeeHealth/sanctuary-patient-app/issues/37

**Comment by iamstevedavis** [comment]
> @iamstevedavis See https://github.com/SanctuaryRefugeeHealth/sanctuary-patient-app/issues/37

Thanks, missed that one. All good there then 👌

**Comment by iamstevedavis** [comment]
https://github.com/SanctuaryRefugeeHealth/sanctuary-patient-api/pull/63
