### ISSUE TITLE
language migration fails

### ISSUE THREAD

**Issue by KrisBraun** [SanctuaryRefugeeHealth/sanctuary-patient-api#59]
Running migrations from an empty database fail:

```
migration file "20200719184339_migrate_message_language.js" failed
migration failed with error: alter table `messages` modify `language` varchar(255) not null - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'language': used in a foreign key constraint 'messages_language_foreign'
Error: ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'language': used in a foreign key constraint 'messages_language_foreign'
```

**Comment by Wiles** [comment]
The `messages_language_foreign` foreign key should not exist when that modification is made. 

My guess is that this is not the first time this migration has failed and this error is only a symptom of the earlier failure.

The migrations all work fine locally for me. Without access to your DB (or a backup of it) I cannot tell much more than that.

**Comment by KrisBraun** [comment]
I'm seeing this when bootstrapping from an empty DB.

**Comment by KrisBraun** [comment]
At least, I think it's empty -- I'm selecting all the tables, dropping them, then running the migrate command.

**Comment by Wiles** [comment]
Check if it is really empty. I tried deleting the tables like that and I had to run the command a few times and skipping errors because of interdependencies.

**Comment by Wiles** [comment]
If you drop them in the following order it should work.

```
DROP TABLE IF EXISTS `knex_migrations`;
DROP TABLE IF EXISTS `knex_migrations_lock`;
DROP TABLE IF EXISTS `replies`;
DROP TABLE IF EXISTS `messages`;
DROP TABLE IF EXISTS `appointments`;
DROP TABLE IF EXISTS `languages`;
DROP TABLE IF EXISTS `users`;
```

**Comment by KrisBraun** [comment]
I'll have to dig more. Ran the above commands, verified no tables exist, then ran `make migrate` and get the error above.

**Comment by Wiles** [comment]
I noticed we are running different versions of the DB in docker (v5.7) and prod (v5.6.44). If I downgrade docker it also fails.

**Comment by Wiles** [comment]
It gives a different error but both might be related to the version mismatch.

```
sanctuary-api | migration file "20200717123217_migrate_patient_language.js" failed
sanctuary-api | migration failed with error: alter table `appointments` add `language` varchar(255) - ER_DUP_FIELDNAME: Duplicate column name 'language'
```

**Comment by Wiles** [comment]
@KrisBraun Give https://github.com/SanctuaryRefugeeHealth/sanctuary-patient-api/pull/60 a try.

**Comment by KrisBraun** [comment]
Thanks, @Wiles, just a note that I gave it a quick try but still hit an error. I think it might be an issue properly publishing the updated container (since prod migrations run using the current container). I'll dig further in the next day or two.
