### ISSUE TITLE
Improve right-to-left language support

### ISSUE THREAD

**Issue by Wiles** [SanctuaryRefugeeHealth/sanctuary-patient-api#61]
Arabic is one of the languages that we support for SMS notifications but we are currently unable to render it properly due to how we mix right-to-left and left-to-right text.

![Screenshot_20200909-140816](https://user-images.githubusercontent.com/5401207/92637819-623f5780-f2a7-11ea-9c8e-a58ad72a0807.png)

**Comment by KrisBraun** [comment]
@mhakmi Is this resolved with your recent changes?

**Comment by mhakmi** [comment]
> @mhakmi Is this resolved with your recent changes?

Yeah, this should be resolved. I see a merged PR from @Wiles that adds `\u200E` (LTR mark) in the Arabic template. So I think this issue should be closed.
